[package]
name = "limit-llm"
version = "0.0.12"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
toml = "0.8"
dirs = "5.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls"] }
bincode = "1.0"
tokio = { version = "1", features = ["full"] }
async-stream = "0.3"
futures = "0.3"
async-trait = "0.1"
bytes = "1.0"
rusqlite = { version = "0.31", features = ["bundled"] }
tiktoken-rs = "0.5"
tracing = "0.1"
[dev-dependencies]
tempfile = "3.8"
mockito = "1.2"
serial_test = "3.0"
